#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20038_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20038_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20040_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20040_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20041_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20041_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20042_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20042_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko619_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko619_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko620_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko620_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko621_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko621_accepted.sorted.dedup.bam

#nice cuffmerge -p 16 -o ~/irs1ko_hypothalamus/mm10/cufflinks/cmout -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -s ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa merge_transcripts.txt

#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20038_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20038_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20040_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20040_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20041_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20041_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/wt20042_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/wt20042_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko619_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko619_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko620_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko620_accepted.sorted.dedup.bam
#nice cufflinks -p 16 --library-type fr-firststrand -o ~/irs1ko_hypothalamus/mm10/cufflinks/irs1ko621_cl -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -b ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko621_accepted.sorted.dedup.bam

#nice cuffmerge -p 16 -o ~/irs1ko_hypothalamus/mm10/cufflinks/cmout -g ~/references/mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/USCS_table.GencodeBasicVM4.gtf -s ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa merge_transcripts.txt

#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/wt20038 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/wt20038_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/wt20040 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/wt20040_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/wt20041 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/wt20041_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/wt20042 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/wt20042_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko619 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko619_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko620 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko620_accepted.sorted.dedup.bam
#nice cuffquant -p 16 --library-type fr-firststrand  -o ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko621 -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf ~/irs1ko_hypothalamus/mm10/tophat2/irs1ko621_accepted.sorted.dedup.bam

#mv ~/irs1ko_hypothalamus/mm10/cuffquant/wt20038/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/wt20038.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/wt20040/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/wt20040.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/wt20041/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/wt20041.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/wt20042/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/wt20042.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko619/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko619.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko620/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko620.cxb
#mv ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko621/abundances.cxb ~/irs1ko_hypothalamus/mm10/cuffquant/irs1ko621.cxb


nice cuffnorm -p 12 --library-type fr-firststrand  -o /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffnorm_without_wt20041 -L wt,irs1ko ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20038.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20040.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20042.cxb /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko619.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko620.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko621.cxb

nice cuffdiff -p 12 --library-type fr-firststrand  -o /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffdiff_without_wt20041  -L wt,irs1ko -M ~/references/mm10/Mus_musculus/UCSC/mm10/Sequence/AbundantSequences/musRibosomal.fa ~/irs1ko_hypothalamus/mm10/cufflinks/cmout/merged.gtf /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20038.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20040.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/wt20042.cxb /beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko619.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko620.cxb,/beegfs/group_lp/home/PEssers/irs1ko_hypothalamus/mm10/cuffquant/irs1ko621.cxb


